import { createClient } from '@supabase/supabase-js';

// Supabase configuration
// Replace with your actual Supabase URL and anon key
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://your-project.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-anon-key';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types (would be generated by Supabase in production)
export interface Database {
    public: {
        Tables: {
            drones: {
                Row: {
                    id: string;
                    name: string;
                    model: string;
                    position: { lat: number; lng: number };
                    battery: number;
                    signal: number;
                    status: string;
                    max_range_km: number;
                    speed_kmh: number;
                    current_mission_id: string | null;
                    owner_id: string;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['drones']['Row'], 'id' | 'created_at'>;
                Update: Partial<Database['public']['Tables']['drones']['Insert']>;
            };
            missions: {
                Row: {
                    id: string;
                    name: string;
                    status: string;
                    polygon: GeoJSON.Polygon;
                    flight_path: GeoJSON.LineString | null;
                    config: {
                        altitude_m: number;
                        overlap_percent: number;
                        camera_fov_deg: number;
                        speed_kmh: number;
                    };
                    assigned_drone_id: string | null;
                    estimated_duration_min: number;
                    estimated_distance_km: number;
                    progress: number;
                    owner_id: string;
                    created_at: string;
                    started_at: string | null;
                    completed_at: string | null;
                };
                Insert: Omit<Database['public']['Tables']['missions']['Row'], 'id' | 'created_at'>;
                Update: Partial<Database['public']['Tables']['missions']['Insert']>;
            };
            nfz_zones: {
                Row: {
                    id: string;
                    name: string;
                    polygon: GeoJSON.Polygon;
                    severity: 'WARNING' | 'RESTRICTED' | 'PROHIBITED';
                    active: boolean;
                };
            };
        };
    };
}
